In [5]:
T = [10, 12, -2, -4, 10, 14, 17, 20, 18, 28, 35, 38, 25, 17, 11, 18]

In [6]:
print(T)

[10, 12, -2, -4, 10, 14, 17, 20, 18, 28, 35, 38, 25, 17, 11, 18]


In [7]:
print(len(T))

16


In [9]:
import numpy as np

T_splited = np.array_split(T, 4)

print(T_splited)

[array([10, 12, -2, -4]), array([10, 14, 17, 20]), array([18, 28, 35, 38]), array([25, 17, 11, 18])]


In [16]:
winter = T_splited[0]
spring = T_splited[1]
summer = T_splited[2]
autnum = T_splited[3]


print(winter)
print(spring)
print(summer)
print(autnum)

[10 12 -2 -4]
[10 14 17 20]
[18 28 35 38]
[25 17 11 18]


In [22]:
print(min(winter))
print(max(winter))

winter_delta = max(winter) - min(winter)
print('winter_delta: ' + str(winter_delta))

print(min(spring))
print(max(spring))

spring_delta = max(spring) - min(spring)
print('spring_delta: ' + str(spring_delta))

print(min(summer))
print(max(summer))

summer_delta = max(summer) - min(summer)
print('summer_delta: ' + str(summer_delta))

print(min(autnum))
print(max(autnum))

autnum_delta = max(autnum) - min(autnum)
print('autnum_delta: ' + str(autnum_delta))

-4
12
winter_delta: 16
10
20
spring_delta: 10
18
38
summer_delta: 20
11
25
autnum_delta: 14


In [23]:
max_delta = max([winter_delta, spring_delta, summer_delta, autnum_delta])

print(max_delta)

20


In [26]:
if winter_delta == max_delta:
    result = 'winter'
elif spring_delta == max_delta:
    result = 'spring'
elif summer_delta == max_delta:
    result = 'summer'
else:
    result = 'autnum'

print(result)

summer


In [45]:
def highest_delta(S):
    # split array on seasons
    seasons = np.array_split(S, 4)
    #extract seasons
    winter_ = seasons[0]
    spring_ = seasons[1]
    summer_ = seasons[2]
    autnum_ = seasons[3]
    # seasons delta
    winter_delta_ = max(winter_) - min(winter_)
    spring_delta_ = max(spring_) - min(spring_)
    summer_delta_ = max(summer_) - min(summer_)
    autnum_delta_ = max(autnum_) - min(autnum_)
    # max delta
    max_delta_ = max([winter_delta_, spring_delta_, summer_delta_, autnum_delta_])
    # find season with highest delta
    if winter_delta_ == max_delta_:
        result = 'winter'
    elif spring_delta_ == max_delta_:
        result = 'spring'
    elif summer_delta_ == max_delta_:
        result = 'summer'
    elif autnum_delta_ == max_delta_:
        result = 'autnum'
    else:
        result = 'error'
    # print result
    print(result)
    pass
    


In [46]:
highest_delta(T)

summer


In [47]:
M = [10, 12, -2, -4, -25, 8, 10, 14, 17, 20, 22, 18, 28, 35, 38, 25, 13, 17, 11, 18]

highest_delta(M)

winter
